# Generated by Django 2.2.7 on 2019-11-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=40)),
                ('points', models.IntegerField()),
                ('description', models.CharField(default='No Description', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/images')),
            ],
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=40)),
                ('points', models.IntegerField()),
                ('description', models.CharField(default='No Description', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/images')),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=40)),
                ('points', models.IntegerField()),
                ('description', models.CharField(default='No Description', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/images')),
            ],
        ),
    ]
