# Generated by Django 3.0.1 on 2020-02-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20200219_2249'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='player',
            field=models.ManyToManyField(to='players.Player'),
        ),
    ]
