# Generated by Django 3.0.1 on 2019-12-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('admissionProfile', models.CharField(max_length=200)),
                ('dischargeProfile', models.CharField(max_length=200)),
                ('schedules', models.CharField(max_length=100)),
                ('courseLength', models.IntegerField()),
                ('courseDescription', models.CharField(max_length=500)),
                ('courseDocument', models.FileField(blank=True, upload_to='temaries/')),
                ('courseBuilder', models.CharField(blank=True, max_length=50, null=True)),
                ('courseCategory', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
