# Generated by Django 2.2.7 on 2019-12-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseCategory',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
