# Generated by Django 3.0.1 on 2020-02-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='body',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='body',
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default='No text'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='text',
            field=models.TextField(default='No text'),
        ),
    ]
