# Generated by Django 3.0.1 on 2020-02-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('courses', '0002_auto_20200213_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentary',
            new_name='Comentary',
        ),
    ]
