# Generated by Django 3.0.1 on 2020-01-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='commentary',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='course_id',
            new_name='course',
        ),
    ]
