# Generated by Django 3.0.1 on 2020-01-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200110_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='commentary_id',
            new_name='commentary',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='player_id',
            new_name='player',
        ),
    ]
