# Generated by Django 3.0.1 on 2020-01-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200110_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='abreviation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
