# Generated by Django 3.0.1 on 2020-01-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200110_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='photo',
            new_name='image',
        ),
    ]
