# Generated by Django 2.2.7 on 2019-11-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(blank=True),
        ),
    ]
