# Generated by Django 3.0.1 on 2020-02-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cluster',
            field=models.CharField(default='Starter', max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='grade',
            field=models.CharField(default='Thinker', max_length=40),
        ),
    ]
