# Generated by Django 3.0.1 on 2020-01-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
    ]
