# Generated by Django 3.0.1 on 2019-12-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20191231_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(null=True, upload_to='user_photos/'),
        ),
    ]
