# Generated by Django 2.2.7 on 2019-11-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20191119_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
