# Generated by Django 3.0.1 on 2020-01-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20200101_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(null=True, upload_to='skyhackDjangoWeb/static/player_profile_images'),
        ),
    ]
